steps:
  - run:
      name: Configure GPG private key for signing project artifacts in OSS Sonatype
      command: |
        echo $SECRING_GPG_ASC_BASE64 | base64 --decode | gpg --batch --no-tty --import --yes
